# Generated by Django 3.2 on 2022-04-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_count',
        ),
    ]
