# Generated by Django 3.2 on 2022-05-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_explanation',
            field=models.TextField(default=''),
        ),
    ]
